### ISSUE TITLE
Missing subfolder "saliency_map"

### ISSUE THREAD

**Issue by deep-introspection** [lrsoenksen/SPL_UD_DL#1]
In the notebook "05_DL_SPL_A_Wide_Field_Feature_Extractor_UglyDucking_Ranking_and_T-SNE" there is an error from the start because one subfolder is missing in "src":

```
from src.saliency_map.saliency_map import SaliencyMap
from src.saliency_map.utils import OpencvIo, Util
```

Would it be possible to add this ```saliency_map``` subfolder to the repository, please?

Thanks!

**Comment by lrsoenksen** [comment]
> In the notebook "05_DL_SPL_A_Wide_Field_Feature_Extractor_UglyDucking_Ranking_and_T-SNE" there is an error from the start because one subfolder is missing in "src":
> 
> ```
> from src.saliency_map.saliency_map import SaliencyMap
> from src.saliency_map.utils import OpencvIo, Util
> ```
> 
> Would it be possible to add this `saliency_map` subfolder to the repository, please?
> 
> Thanks!

Solved! Thanks for noticing it

**Comment by deep-introspection** [comment]
Thanks a lot! It's working perfectly now.
