### ISSUE TITLE
Cannot download MODELS (Direct Download)

### ISSUE THREAD

**Issue by emwai123** [lrsoenksen/SPL_UD_DL#2]
I cannot download models from Dropbox.
https://www.dropbox.com/s/crib0kyjl5z0vli/output.zip?dl=0
It says "This item was deleted".

Thanks.

**Comment by lrsoenksen** [comment]
Model weight files directly from this link: https://www.dropbox.com/s/n0aj1ezzh99uyjd/Models.zip?dl=0. After download place in the main project folder and unzip. This was recently updated to allow for more people to download it. Sorry for the previous inconvenience =)

**Comment by emwai123** [comment]
Thank you for your help!!
