### ISSUE TITLE
Link to data missing | 01_DL_SPL_Detection_Basic_Model_Creator.ipynb

### ISSUE THREAD

**Issue by myrinx** [lrsoenksen/SPL_UD_DL#3]
The link to the Dataset: "MIT's SKIN proyect Suspicious Pigmented Lesion Database Data" is missing. Is that available for use?

**Comment by lrsoenksen** [comment]
The data is available and possible to share under a data usage agreement that requires to be pursued directly with MIT and your academic institution. There are some restrictions in terms of its use and where the data can be hosted, which are handled on a one-to-one basis please email directly to the corresponding author of the publication. The provided pre-trained models can be used with your own data for inference.
